# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
 services.fstrim.enable = true;


  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "thunderbolt" "vmd" "nvme" "sd_mod" "rtsx_pci_sdmmc"];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };



  fileSystems."/" =
    {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  fileSystems."/xdrive" =
    {
      device = "/dev/disk/by-label/xdrive";
      fsType = "ext4";
    };

  swapDevices = [{ device = "/.swapfile"; } ];
        powerManagement = {
          enable = true;
          powertop.enable = true;
          cpuFreqGovernor = lib.mkDefault "ondemand";
        };
        # high-resolution display
        #
        hardware = {
          # pulseaudio = {enable = true; package = pkgs.pulseaudioFull;};
          bluetooth = {
            enable = true;
            settings = {
              General = {
                Enable = "Source,Sink,Media,Socket";
              };
            };
          };


        };

        environment.variables = {
          # VDPAU_DRIVER = lib.mkIf config.hardware.graphics.enable (lib.mkDefault "va_gl");
          VDPAU_DRIVER = lib.mkIf config.hardware.graphics.enable (lib.mkDefault "va_gl");
        };


}
