# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/6813901b-f560-44d1-a06c-5d7a3503b5ae";
      fsType = "ext4";
      };

      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/1FE8-921B";
        fsType = "vfat";
        };


        powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
        hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
        # high-resolution display
        hardware.video.hidpi.enable = lib.mkDefault true;
        hardware.bluetooth.enable = true;
}
